name: cargo test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Lint check
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose
