name: Release
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]
jobs:
  publish:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      (startsWith(github.event.workflow_run.head_branch, 'refs/tags/v') ||
      startsWith(github.event.workflow_run.head_branch, 'refs/tags/test-'))
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Publish to crates.io
      #   run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
